#!/bin/sh
set -e
# set -x

VERSION_FILE="src/version.h"

rm -f $VERSION_FILE

export LIBSESSION_NODEJS_VERSION=$(node -p "require('./package.json').version")
LIBSESSION_NODEJS_COMMIT=$(git rev-parse HEAD)

echo "Updating LIBSESSION_NODEJS_VERSION: $LIBSESSION_NODEJS_VERSION"
echo "Updating LIBSESSION_NODEJS_COMMIT: $LIBSESSION_NODEJS_COMMIT"


echo "const char* LIBSESSION_NODEJS_VERSION = \"$LIBSESSION_NODEJS_VERSION\";" > $VERSION_FILE
echo "const char* LIBSESSION_NODEJS_COMMIT = \"$LIBSESSION_NODEJS_COMMIT\";" >> $VERSION_FILE

echo "\n'$VERSION_FILE' updated to:"
cat $VERSION_FILE

